export const MockDataTransactions = [
  {
    date: new Date("2025-08-01T09:30:00"),
    account: "Cash",
    category: "🍜 Food",
    note: "Lunch at cafeteria",
    currency: "THB",
    type: "Expense",
    amount: 120,
  },
  {
    date: new Date("2025-08-02T18:15:00"),
    account: "Bank",
    category: "🌐 work salary",
    note: "Monthly salary credited",
    currency: "THB",
    type: "Income",
    amount: 30000,
  },
  {
    date: new Date("2025-08-03T08:45:00"),
    account: "Wallet",
    category: "🚖 Transport",
    note: "Grab taxi ride",
    currency: "THB",
    type: "Expense",
    amount: 180,
  },
  {
    date: new Date("2025-08-04T14:10:00"),
    account: "Cash",
    category: "☕ coffee",
    note: "Coffee with friends",
    currency: "THB",
    type: "Expense",
    amount: 75,
  },
  {
    date: new Date("2025-08-05T10:00:00"),
    account: "Bank",
    category: "🤑 Allowance",
    note: "Monthly allowance from family",
    currency: "THB",
    type: "Income",
    amount: 5000,
  },
  {
    date: new Date("2025-08-06T16:20:00"),
    account: "Cash",
    category: "💊 medical",
    note: "Medicine purchase",
    currency: "THB",
    type: "Expense",
    amount: 350,
  },
  {
    date: new Date("2025-08-07T19:45:00"),
    account: "Bank",
    category: "🏅 Bonus",
    note: "Quarterly performance bonus",
    currency: "THB",
    type: "Income",
    amount: 8000,
  },
  {
    date: new Date("2025-08-08T22:00:00"),
    account: "Cash",
    category: "🏪 7-11",
    note: "Snacks and drinks",
    currency: "THB",
    type: "Expense",
    amount: 200,
  },
  {
    date: new Date("2025-08-09T20:30:00"),
    account: "Wallet",
    category: "🎉 New Year",
    note: "Party expenses",
    currency: "THB",
    type: "Expense",
    amount: 1500,
  },
  {
    date: new Date("2025-08-10T11:25:00"),
    account: "Bank",
    category: "💰 TA Salary",
    note: "Teaching Assistant monthly salary",
    currency: "THB",
    type: "Income",
    amount: 12000,
  },
];
